/*
   This file is part of O-Strata, an Ouaricon Audio plugin.
   Copyright (C) 2026  Ouaricon Audio

   SPDX-License-Identifier: AGPL-3.0-or-later
   (full AGPL header block verbatim from plugins/O-Prism/Source/PluginEditor.h)
*/
/*
  ==============================================================================

    PluginEditor.h — TEMPLATE v1 (generated by ui-finalization-agent, 2026-09-07)
    O-Strata - 3D-Geometry Wavetable Synthesizer (fork of O-Prism v1.24.0)
    Ouaricon Audio — Developer: Taylor Brook

    THIS IS A DELTA TEMPLATE, not a copy-paste file. Stage 3 gui-agent starts
    from plugins/O-Prism/Source/PluginEditor.h and applies the changes marked
    NEW / REMOVED below. Lines marked "unchanged from O-Prism" are kept as-is.

    Parameter plumbing (parameter-spec.md "Relay / attachment plumbing"):
      slider relays  = PrismParamIds::allSliderIds()  → 187 (O-Prism 141 − 2 Table + 48 Geometry)
      toggle relays  = 30 (delaySync 1 + lfo{1..4}{Sync,FreeRun} 8 + 5 bypass + 16 modSlot?On)
      TOTAL relays   = 217 = total attachments, for 219 APVTS parameters
      (delayDivision, stereoWidth have no relay in O-Prism either — carried over)

    Every one of the 48 geometry relays is a juce::WebSliderRelay created by the
    unchanged generic loop; choice params ride slider relays exactly as
    oscAWarpType does. There is NO per-parameter member for geometry.

  ==============================================================================
*/

#pragma once
#include <JuceHeader.h>
#include "PluginProcessor.h"
#include "PrismParamIds.h"     // NEW contents: see the PrismParamIds delta in v1-PluginEditor-TEMPLATE.cpp

class OStrataAudioProcessorEditor : public juce::AudioProcessorEditor,      // renamed from OPrismAudioProcessorEditor
                                    private juce::Timer
{
public:
    explicit OStrataAudioProcessorEditor (OStrataAudioProcessor&);
    ~OStrataAudioProcessorEditor() override;

    void paint (juce::Graphics&) override;      // unchanged from O-Prism (WebView fills the editor)
    void resized() override;                    // unchanged from O-Prism

private:
    OStrataAudioProcessor& processorRef;

    // ═══════════════════════════════════════════════════════════════════
    // CRITICAL: Member declaration order (C++ destroys in reverse)
    // 1. Relays declared FIRST  → destroyed LAST
    // 2. WebView SECOND         → destroyed SECOND
    // 3. Attachments LAST       → destroyed FIRST (WebView still alive — safe;
    //    attachments call into the WebView during destruction; wrong order
    //    crashes only in release builds on plugin reload)
    // Unchanged from O-Prism — the vectors simply grow.
    // ═══════════════════════════════════════════════════════════════════

    // 1️⃣ RELAYS FIRST (destroyed last)
    std::vector<std::unique_ptr<juce::WebSliderRelay>> sliderRelays;                     // 187 (was 141)
    std::unique_ptr<juce::WebToggleButtonRelay> delaySyncRelay;
    std::vector<std::unique_ptr<juce::WebToggleButtonRelay>> lfoSyncRelays;              // 4
    std::vector<std::unique_ptr<juce::WebToggleButtonRelay>> lfoFreeRunRelays;           // 4
    std::vector<std::unique_ptr<juce::WebToggleButtonRelay>> bypassRelays;               // 5
    std::vector<std::unique_ptr<juce::WebToggleButtonRelay>> modSlotToggleRelays;        // 16

    // 2️⃣ WEBVIEW SECOND (destroyed second)
    std::unique_ptr<juce::WebBrowserComponent> webView;

    // 3️⃣ ATTACHMENTS LAST (destroyed first — WebView still alive)
    std::vector<std::unique_ptr<juce::WebSliderParameterAttachment>> sliderAttachments;  // 187
    std::unique_ptr<juce::WebToggleButtonParameterAttachment> delaySyncAttachment;
    std::vector<std::unique_ptr<juce::WebToggleButtonParameterAttachment>> lfoSyncAttachments;
    std::vector<std::unique_ptr<juce::WebToggleButtonParameterAttachment>> lfoFreeRunAttachments;
    std::vector<std::unique_ptr<juce::WebToggleButtonParameterAttachment>> bypassAttachments;
    std::vector<std::unique_ptr<juce::WebToggleButtonParameterAttachment>> modSlotToggleAttachments;

    // ── Resource provider (unchanged signature; body delta in the .cpp) ──
    std::optional<juce::WebBrowserComponent::Resource>
        getResource (const juce::String& url);

    // ── Native function registration (unchanged signature; body delta in the .cpp) ──
    juce::WebBrowserComponent::Options addNativeFunctions (
        juce::WebBrowserComponent::Options options);

    // ═══════════════════════════════════════════════════════════════════
    // NEW — 30 Hz push path (ARCHITECTURE Decision 7, UI-01/UI-04/UI-05)
    // timerCallback() no longer calls evaluateJavascript (JUCE #1415); it emits
    // change-gated events through webView->emitEventIfBrowserIsVisible().
    // ═══════════════════════════════════════════════════════════════════
    void timerCallback() override;

    // Held notes (TrueKeys) — was evaluateJavascript("window.updateHeldNotes(...)")
    std::vector<std::pair<int, double>> lastSentNotes;                              // unchanged member, new transport

    // Playhead {osc, frame, phase}: emitted only when it changed since the last tick
    struct PlayheadSnapshot { int frame = -1; float phase = -1.0f; };
    PlayheadSnapshot lastPlayhead[2];

    // Bake progress {osc, progress, baking}: 10 Hz while in flight (every 3rd tick)
    float lastBakeProgress[2] { -1.0f, -1.0f };
    bool  lastBaking[2]       { false, false };
    int   tickCounter = 0;

    // geometryState re-push gate: bakeGeneration[osc] or importRevision changed
    // → build + emit the view payload (64×64 Float32 base64, contour/orbit
    // polylines, mesh .bin URL with the generation in the path). Covers preset
    // apply and setStateInformation with the editor open (UI-05; memory
    // pattern_webview_one_shot_state_push_stale_on_preset_load).
    int  lastBakeGeneration[2] { -1, -1 };
    int  lastImportRevision     = -1;
    void pushGeometryState (int osc);                                             // NEW
    void pushPlayheadIfChanged (int osc);                                         // NEW
    void pushBakeProgressIfChanged (int osc);                                     // NEW
    void pushHeldNotesIfChanged();                                                // NEW (was the body of timerCallback)

    // Per-osc view mode mirrored from the page (⬡ = 0, ≋ = 1) — UI state, not a
    // parameter; lets pushGeometryState() skip the stacked-frame table when the
    // 3D view is showing. NOT persisted.
    int viewMode[2] { 0, 0 };

    // Drag-and-drop import assembly (JS streams ≤ 4 MB base64 chunks; bytes are
    // parsed in the bake job, never here — Decision 6)
    juce::MemoryOutputStream pendingImport[2];
    juce::String             pendingImportName[2];

    // ── REMOVED from O-Prism ──
    //   (nothing in the header: the 14 wavetable-library native fns were registered
    //    inline in addNativeFunctions(); their editor-side state lived in the processor)

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (OStrataAudioProcessorEditor)
};
