/*
   This file is part of O-Strata, an Ouaricon Audio plugin.
   Copyright (C) 2026  Ouaricon Audio

   SPDX-License-Identifier: AGPL-3.0-or-later
   (full AGPL header block verbatim from plugins/O-Strata/Source/PluginEditor.cpp)
*/
/*
  ==============================================================================

    PluginEditor.cpp — TEMPLATE v2 (generated by ui-finalization-agent, 2026-09-10)
    O-Strata — DELTA against the EXISTING fork's plugins/O-Strata/Source/PluginEditor.cpp

    Stage 3 gui-agent: start from the fork's file and apply the sections below
    in order. "unchanged" = keep verbatim. Window: setSize (1200, 800) — from
    v2-ui.yaml `window:` (unchanged from O-Prism).

    Idioms are the fork's own: WebSliderRelay / WebToggleButtonRelay vectors
    built from StrataParamIds, `.withOptionsFrom()` for every relay, the
    3-argument attachment constructors (parameter, relay, nullptr — JUCE 8),
    FileChooser::launchAsync with Component::SafePointer and NO complete() on
    the dead path. What is NEW: a WebComboBoxRelay group, three native
    functions, and a timer that PUSHES with emitEventIfBrowserIsVisible.

  ==============================================================================
*/

#include "PluginEditor.h"
#include "EmbeddedTunings.h"
#include "TuningExporter.h"
#include "dsp/ModulationMatrix.h"

// ═══════════════════════════════════════════════════════════════════
// §0  StrataParamIds.h DELTA (Stage 1 second pass — shown here because the
//     editor's relay loops are driven by it; parameter-spec.md v2 "APVTS order")
// ═══════════════════════════════════════════════════════════════════
/*
    // ─── Oscillator SLIDER IDs (prefix + shared suffixes) — 24 per oscillator ───
    inline juce::StringArray oscIds (const juce::String& prefix)
    {
        juce::StringArray ids;
        for (const auto* s : { "Pos", "Level", "Pan", "Coarse", "Fine", "Phase",
                                "Unison", "Detune", "Width", "WarpType", "WarpAmt",   // 11 carried over (Pos = Orbit Size)
                                // ── NEW: Terrain block floats (parameter-spec.md v2 rows 13–18) ──
                                "TerFreq", "TerModX", "TerModY", "TerTrack", "TerSat", "TerBlur",
                                // ── NEW: Orbit block floats (rows 21–27) ──
                                "OrbAspect", "OrbRot", "OrbCX", "OrbCY", "OrbMod", "OrbFeedback", "OrbFbDamp" })
            ids.add (prefix + s);
        return ids;                                                        // 24
    }
    //  REMOVED (all 24 baked suffixes): "GeoSource", "GeoFrames", "GeoDrive",
    //  "Mesh", "MeshTiltX", "MeshTiltY", "MeshPhi", "MeshUnwrap", "MeshLoop",
    //  "VolField", "VolOrbit", "VolSweepAxis", "VolSweepRange", "VolDetail",
    //  "Terrain"*, "TerOrbit", "TerCX", "TerCY", "TerAspect", "TerRot",
    //  "TerSweepAxis", "TerSweepRange", "TerBlur"*, "TerEdge"*
    //  (* = ID kept, but it is now a COMBO id or a float with the v2 meaning)

    // ─── NEW: Oscillator COMBOBOX IDs — the 4 Choice params per oscillator ───
    inline juce::StringArray oscComboIds (const juce::String& prefix)
    {
        juce::StringArray ids;
        for (const auto* s : { "Terrain", "TerEdge", "Orbit", "Quality" })   // rows 12, 19, 20, 28
            ids.add (prefix + s);
        return ids;                                                        // 4
    }

    inline juce::StringArray allComboIds()
    {
        juce::StringArray all;
        all.addArray (oscComboIds ("oscA"));                                // 4
        all.addArray (oscComboIds ("oscB"));                                // 4
        return all;                                                         // 8
    }

    // allSliderIds(): the two oscIds() lines now contribute 24 each (comment
    // "// 35" → "// 24"); the trailing total "// 188" → "// 166". Everything
    // else in the function is unchanged.
*/

// ═══════════════════════════════════════════════════════════════════
// §1  Toggle relay helpers — unchanged
// ═══════════════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════════════
// §2  Resource provider — +1 route. makeBinaryResource() unchanged.
// ═══════════════════════════════════════════════════════════════════
/*
std::optional<juce::WebBrowserComponent::Resource>
OStrataAudioProcessorEditor::getResource (const juce::String& url)
{
    if (url == "/" || url == "/index.html")            … unchanged
    if (url == "/js/i18n.js")                           … unchanged (EMBEDDED and SERVED — check-i18n assertion 8)
    if (url == "/js/juce/index.js")                     … unchanged
    if (url == "/js/juce/check_native_interop.js")      … unchanged

    // NEW — the Terrain tab's botanical plate (CSS background on .terrain-botanical).
    // juce_add_binary_data strips nothing here (no hyphen in the file name), so the
    // symbol is the file name with `.` → `_` (memory critical_binary_data_strips_hyphens).
    if (url == "/img/shell_conchologiaiconi12reev_0090.png")
        return makeBinaryResource (BinaryData::shell_conchologiaiconi12reev_0090_png,
                                   BinaryData::shell_conchologiaiconi12reev_0090_pngSize, "image/png");

    return std::nullopt;
}
*/

// ═══════════════════════════════════════════════════════════════════
// §3  Native functions — REMOVE 2, ADD 3. Everything else in
//     addNativeFunctions() (language, tuning, Scala/KBM, generators,
//     embedded tunings, export, mod names, preset manager) is unchanged.
// ═══════════════════════════════════════════════════════════════════
/*
    // REMOVED (with WavetableData / getActiveOscTable, Phase 2.1):
    //   options = options.withNativeFunction ("getActiveOscInfo",  …);
    //   options = options.withNativeFunction ("getActiveOscFrame", …);

    // ── NEW: Import… button → native FileChooser (v2-ui.yaml interactions.import_btn) ──
    // Argument 0: "A" | "B" (the Terrain tab's active oscillator). The page does NOT
    // set osc?Terrain itself; the processor's import job sets it to Imported… once
    // the PNG has decoded, so a cancelled chooser leaves the parameter alone.
    options = options.withNativeFunction ("chooseTerrainImage",
        [this] (const juce::Array<juce::var>& args, auto complete)
        {
            const int osc = (args.size() > 0 && args[0].toString() == "B") ? 1 : 0;

            auto chooser = std::make_shared<juce::FileChooser> (
                "Import Terrain Image",
                juce::File::getSpecialLocation (juce::File::userPicturesDirectory),
                "*.png");

            juce::Component::SafePointer<OStrataAudioProcessorEditor> safeThis (this);
            chooser->launchAsync (juce::FileBrowserComponent::openMode
                                | juce::FileBrowserComponent::canSelectFiles,
                [safeThis, chooser, complete, osc] (const juce::FileChooser& fc)
                {
                    if (safeThis == nullptr)
                        return; // editor destroyed — `complete` is owned by the dead WebView, never call it
                               // (memory pattern_webview_launchasync_safepointer_no_complete)
                    auto file = fc.getResult();
                    if (! file.existsAsFile()) { complete (false); return; }

                    juce::MemoryBlock bytes;
                    if (! file.loadFileAsData (bytes)) { complete (false); return; }

                    // Processor API (Stage 2, Core 8): stores the blob under importLock
                    // (message thread), bumps imageGeneration[osc], decodes + pre-blurs on
                    // the background thread, then sets osc?Terrain = Imported… and bumps
                    // the terrain generation so the heightmap is re-pushed.
                    const bool ok = safeThis->processorRef.submitTerrainImport (osc, file.getFileName(), bytes, file);
                    safeThis->repushPending = true;
                    complete (ok);
                });
        });

    // ── NEW: PNG drop → bytes streamed from the page (v2-ui.yaml interactions.view_3d.drop) ──
    // WKWebView strips file paths from the DataTransfer, so the page reads the
    // File through webkitGetAsEntry and sends base64 (memory critical_webview_drag_drop_macos).
    // Args: osc "A"|"B", fileName, base64. Path-linking (embedded="0") is not
    // possible for a drop — the blob is always embedded (≤ 2 MB) or refused.
    options = options.withNativeFunction ("importTerrainImageData",
        [this] (const juce::Array<juce::var>& args, auto complete)
        {
            if (args.size() < 3) { complete (false); return; }
            const int osc = args[0].toString() == "B" ? 1 : 0;
            const juce::String name = args[1].toString();

            juce::MemoryOutputStream decoded;
            if (! juce::Base64::convertFromBase64 (decoded, args[2].toString())) { complete (false); return; }
            if (decoded.getDataSize() > 2 * 1024 * 1024) { complete (false); return; }   // FUNC-08 cap: no path to link to

            juce::MemoryBlock bytes (decoded.getData(), decoded.getDataSize());
            const bool ok = processorRef.submitTerrainImport (osc, name, bytes, juce::File());
            repushPending = true;
            complete (ok);
        });

    // ── NEW: the page asks for a full re-push (after preset load, and once at boot) ──
    options = options.withNativeFunction ("requestTerrainRepush",
        [this] (const juce::Array<juce::var>&, auto complete)
        {
            repushPending = true;
            complete (true);
        });
*/

// ═══════════════════════════════════════════════════════════════════
// §4  Constructor — the comboBox relay group is threaded through the three
//     existing steps. Everything not shown is unchanged.
// ═══════════════════════════════════════════════════════════════════
/*
OStrataAudioProcessorEditor::OStrataAudioProcessorEditor (OStrataAudioProcessor& p)
    : AudioProcessorEditor (p),
      processorRef (p)
{
    // Step 1: Create relays (before WebView)
    auto sliderIds    = StrataParamIds::allSliderIds();      // 166
    auto comboIds     = StrataParamIds::allComboIds();       // NEW — 8
    auto bypassIds    = StrataParamIds::bypassToggleIds();
    auto modToggleIds = StrataParamIds::modSlotToggleIds();
    …lfoSyncIds / lfoFreeRunIds unchanged…

    for (const auto& id : sliderIds)
        sliderRelays.push_back (std::make_unique<juce::WebSliderRelay> (id));

    // NEW — comboBox relays: the page's <select> options come from the
    // AudioParameterChoice through this relay's propertiesChanged push, so the
    // JS lists in index.html are only pre-push fallbacks.
    for (const auto& id : comboIds)
        comboRelays.push_back (std::make_unique<juce::WebComboBoxRelay> (id));

    …toggle relays unchanged…

    // Step 2: Build WebView options with relays + native functions
    auto options = juce::WebBrowserComponent::Options{}
        .withBackend (juce::WebBrowserComponent::Options::Backend::webview2)
        .withNativeIntegrationEnabled()
        .withResourceProvider ([this] (const auto& url) { return getResource (url); });

    for (const auto& relay : sliderRelays)
        options = options.withOptionsFrom (*relay);

    for (const auto& relay : comboRelays)                    // NEW
        options = options.withOptionsFrom (*relay);

    …toggle relay options, addNativeFunctions (options), JUCE_WINDOWS withUserDataFolder ("OStrata_WebView") unchanged…

    webView = std::make_unique<juce::WebBrowserComponent> (options);

    // Step 3: Create attachments (after WebView)
    …slider attachments unchanged; the jassert now reads 166:
    jassert (sliderAttachments.size() == sliderRelays.size());   // 166 — allSliderIds() and createParameterLayout() must agree

    // NEW — comboBox attachments (3-argument form, as the sliders)
    for (int i = 0; i < comboIds.size(); ++i)
    {
        if (auto* param = processorRef.getAPVTS().getParameter (comboIds[i]))
            comboAttachments.push_back (
                std::make_unique<juce::WebComboBoxParameterAttachment> (
                    *param, *comboRelays[static_cast<size_t> (i)], nullptr));
    }
    jassert (comboAttachments.size() == comboRelays.size());     // 8

    …toggle attachments unchanged…

    // Step 4: Show WebView + navigate — unchanged
    addAndMakeVisible (*webView);
    webView->goToURL (juce::WebBrowserComponent::getResourceProviderRoot());
    setSize (1200, 800);                                     // v2-ui.yaml window: 1200 × 800, not resizable
    startTimerHz (30);                                       // unchanged rate; the callback is new (§5)
}
*/

// ═══════════════════════════════════════════════════════════════════
// §5  Timer — PUSH, never evaluateJavascript. Replaces the whole body of the
//     fork's timerCallback(). Every emit goes through emitEventIfBrowserIsVisible
//     (payloads are DROPPED while the WebView is hidden, which is the point:
//     memory critical_webview_completion_gated_on_isvisible) and is change-gated
//     so an idle plugin emits nothing. The page re-requests everything after a
//     preset load (requestTerrainRepush) so a drop while hidden is never a
//     stale view.
// ═══════════════════════════════════════════════════════════════════
/*
void OStrataAudioProcessorEditor::timerCallback()
{
    if (webView == nullptr)
        return;

    const bool force = repushPending;
    repushPending = false;

    for (int osc = 0; osc < 2; ++osc)
    {
        pushHeightmap    (osc, force);
        pushStatus       (osc, force);
        pushTerrainState (osc, force);
    }
    pushHeldNotes (force);
}

// {osc:"A"|"B", theta, x, y} — < 100 bytes; theta in [0,1) is the most-recent
// voice's phase accumulator, (x, y) the displaced orbit point actually read
// (Core 10 CycleCapture). Change-gated per oscillator.
void OStrataAudioProcessorEditor::pushTerrainState (int osc, bool force)
{
    PlayheadSnapshot s;
    if (! processorRef.getTerrainPlayhead (osc, s.theta, s.x, s.y))   // false = no voice sounding → nothing to push
        return;
    if (! force && s == lastPlayhead[osc])
        return;
    lastPlayhead[osc] = s;

    auto* obj = new juce::DynamicObject();
    obj->setProperty ("osc",   osc == 0 ? "A" : "B");
    obj->setProperty ("theta", s.theta);
    obj->setProperty ("x",     s.x);
    obj->setProperty ("y",     s.y);
    webView->emitEventIfBrowserIsVisible ("terrainState", juce::var (obj));
}

// {osc, n:64, data:<base64 of 64×64 Float32 little-endian>} — 16 KB raw,
// ~22 KB base64 — only when the processor's terrain generation moved
// (terrain-parameter change, PNG import/decoded, Chebyshev swap, preset apply).
void OStrataAudioProcessorEditor::pushHeightmap (int osc, bool force)
{
    const uint32_t gen = processorRef.getTerrainGeneration (osc);
    if (! force && gen == lastHeightmapGeneration[osc])
        return;
    lastHeightmapGeneration[osc] = gen;

    std::array<float, 64 * 64> hm {};
    processorRef.copyTerrainHeightmap (osc, hm.data(), 64);   // samples the ACTIVE surface: PNG / analytic / truncated Chebyshev, pitch-tracked at C4

    // IN-16 lesson: juce::String would emit "nan"/"inf" — scrub before encoding.
    for (auto& v : hm) if (! std::isfinite (v)) v = 0.0f;

    auto* obj = new juce::DynamicObject();
    obj->setProperty ("osc",  osc == 0 ? "A" : "B");
    obj->setProperty ("n",    64);
    obj->setProperty ("data", juce::Base64::toBase64 (hm.data(), hm.size() * sizeof (float)));
    webView->emitEventIfBrowserIsVisible ("terrainHeightmap", juce::var (obj));
}

// {osc, sourceMissing, fit, partials, approx} — readout facts only C++ knows.
void OStrataAudioProcessorEditor::pushStatus (int osc, bool force)
{
    const auto st = processorRef.getTerrainStatus (osc);     // struct { bool sourceMissing; int fitPercent; int partialsAtC4; bool approximate; }

    auto* obj = new juce::DynamicObject();
    obj->setProperty ("osc",           osc == 0 ? "A" : "B");
    obj->setProperty ("sourceMissing", st.sourceMissing);
    obj->setProperty ("fit",           st.fitPercent);
    obj->setProperty ("partials",      st.partialsAtC4);
    obj->setProperty ("approx",        st.approximate);
    juce::var payload (obj);

    const auto json = juce::JSON::toString (payload, true);
    if (! force && json == lastStatusJson[osc])
        return;
    lastStatusJson[osc] = json;
    webView->emitEventIfBrowserIsVisible ("terrainStatus", payload);
}

// {notes:[midi…], freqs:[hz…]} — was evaluateJavascript("window.updateHeldNotes(…)").
// The page's O-Prism tuning IIFE still consumes window.updateHeldNotes(notes, freqs);
// the listener in index.html forwards to it.
void OStrataAudioProcessorEditor::pushHeldNotes (bool force)
{
    auto currentNotes = processorRef.getActiveNotes();
    if (! force && currentNotes == lastSentNotes)
        return;
    lastSentNotes = currentNotes;

    juce::Array<juce::var> notes, freqs;
    for (const auto& n : currentNotes) { notes.add (n.first); freqs.add (n.second); }

    auto* obj = new juce::DynamicObject();
    obj->setProperty ("notes", notes);
    obj->setProperty ("freqs", freqs);
    webView->emitEventIfBrowserIsVisible ("heldNotes", juce::var (obj));
}

void OStrataAudioProcessorEditor::repushAll() { repushPending = true; }   // called by the processor after preset apply / setStateInformation (UI-04)
*/

// ═══════════════════════════════════════════════════════════════════
// §6  Destructor / paint / resized — unchanged (stopTimer(); WebView fills the editor).
// ═══════════════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════════════
// §7  Processor API this template assumes (Stage 2 delivers; names are proposals)
// ═══════════════════════════════════════════════════════════════════
/*
    // Core 10 CycleCapture → view (message thread reads a seqlock'd snapshot)
    bool     getTerrainPlayhead   (int osc, float& theta, float& x, float& y) const;   // false when no voice sounds
    // Core 3/7/8 → view surface
    uint32_t getTerrainGeneration (int osc) const;                                     // bumps on terrain-param change, import, Chebyshev swap, state restore
    void     copyTerrainHeightmap (int osc, float* dst64x64, int n) const;             // active surface at C4, pitch tracking applied, [-1,1]
    struct TerrainStatus { bool sourceMissing = false; int fitPercent = 100; int partialsAtC4 = 12; bool approximate = false; };
    TerrainStatus getTerrainStatus (int osc) const;
    // Core 8 import (FUNC-08)
    bool     submitTerrainImport  (int osc, const juce::String& name, const juce::MemoryBlock& png, const juce::File& sourceOrEmpty);
    // Preset apply / setStateInformation notify the editor: if (auto* ed = dynamic_cast<OStrataAudioProcessorEditor*> (getActiveEditor())) ed->repushAll();
    //   — or, simpler and thread-safe, bump every generation counter so the change gates fire on the next tick.
*/
