/*
   This file is part of O-Strata, an Ouaricon Audio plugin.
   Copyright (C) 2026  Ouaricon Audio

   SPDX-License-Identifier: AGPL-3.0-or-later
   (full AGPL header block verbatim from plugins/O-Strata/Source/PluginEditor.h)
*/
/*
  ==============================================================================

    PluginEditor.h — TEMPLATE v2 (generated by ui-finalization-agent, 2026-09-10)
    O-Strata - Microtonal Wave-Terrain Synthesizer (fork of O-Prism, UI re-forked
    from v1.26.0 at Stage 3)

    THIS IS A DELTA against the EXISTING fork's plugins/O-Strata/Source/PluginEditor.h
    (the v1.24.0-based file that already carries the OStrata rename, the vector
    relay groups and the JUCE_WEB_BROWSER-guarded createEditor()). Lines marked
    "unchanged" are kept as-is; NEW / REMOVED lines are the whole diff. It is
    NOT a copy-paste file — gui-agent applies it during Stage 3.

    Parameter plumbing (parameter-spec.md v2 "Relay / attachment plumbing"):
      slider relays  = StrataParamIds::allSliderIds()  → 166 (fork 188 − 70 + 48)
      combo relays   = StrataParamIds::allComboIds()   →   8 (NEW: osc{A,B}{Terrain,TerEdge,Orbit,Quality})
      toggle relays  = 30 (delaySync 1 + lfo{1..4}{Sync,FreeRun} 8 + 5 bypass + 16 modSlot?On) — unchanged
      TOTAL          = 204 relays = 204 attachments, for 205 APVTS parameters
      (stereoWidth has no UI control, as in O-Prism)

    The 26 new Float parameters ride the unchanged generic slider loop. The 8
    new Choice parameters are the ONLY comboBox relays in the plugin; every
    inherited choice (WarpType, filter types, LFO shapes …) stays on a slider
    relay so the O-Prism bindings carry over untouched.

  ==============================================================================
*/

#pragma once
#include <JuceHeader.h>
#include "PluginProcessor.h"
#include "StrataParamIds.h"     // NEW contents: oscIds() re-parameterised + oscComboIds()/allComboIds() — see §0 of the .cpp template

class OStrataAudioProcessorEditor : public juce::AudioProcessorEditor,      // unchanged
                                    private juce::Timer
{
public:
    explicit OStrataAudioProcessorEditor (OStrataAudioProcessor&);
    ~OStrataAudioProcessorEditor() override;

    void paint (juce::Graphics&) override;      // unchanged (WebView fills the editor)
    void resized() override;                    // unchanged

private:
    OStrataAudioProcessor& processorRef;

    // ═══════════════════════════════════════════════════════════════════
    // CRITICAL: Member declaration order (C++ destroys in reverse)
    // 1. Relays declared FIRST  → destroyed LAST
    // 2. WebView SECOND         → destroyed SECOND
    // 3. Attachments LAST       → destroyed FIRST (WebView still alive — safe;
    //    attachments call into the WebView during destruction; wrong order
    //    crashes only in release builds on plugin reload)
    // Unchanged from the fork — one relay group and one attachment group are ADDED.
    // ═══════════════════════════════════════════════════════════════════

    // 1️⃣ RELAYS FIRST (destroyed last)
    std::vector<std::unique_ptr<juce::WebSliderRelay>> sliderRelays;                     // 166 (was 188 with the baked set)
    std::vector<std::unique_ptr<juce::WebComboBoxRelay>> comboRelays;                    // NEW — 8
    std::unique_ptr<juce::WebToggleButtonRelay> delaySyncRelay;
    std::vector<std::unique_ptr<juce::WebToggleButtonRelay>> lfoSyncRelays;              // 4
    std::vector<std::unique_ptr<juce::WebToggleButtonRelay>> lfoFreeRunRelays;           // 4
    std::vector<std::unique_ptr<juce::WebToggleButtonRelay>> bypassRelays;               // 5
    std::vector<std::unique_ptr<juce::WebToggleButtonRelay>> modSlotToggleRelays;        // 16

    // 2️⃣ WEBVIEW SECOND (destroyed second)
    std::unique_ptr<juce::WebBrowserComponent> webView;

    // 3️⃣ ATTACHMENTS LAST (destroyed first — WebView still alive)
    std::vector<std::unique_ptr<juce::WebSliderParameterAttachment>> sliderAttachments;  // 166
    std::vector<std::unique_ptr<juce::WebComboBoxParameterAttachment>> comboAttachments; // NEW — 8
    std::unique_ptr<juce::WebToggleButtonParameterAttachment> delaySyncAttachment;
    std::vector<std::unique_ptr<juce::WebToggleButtonParameterAttachment>> lfoSyncAttachments;
    std::vector<std::unique_ptr<juce::WebToggleButtonParameterAttachment>> lfoFreeRunAttachments;
    std::vector<std::unique_ptr<juce::WebToggleButtonParameterAttachment>> bypassAttachments;
    std::vector<std::unique_ptr<juce::WebToggleButtonParameterAttachment>> modSlotToggleAttachments;

    // ── Resource provider (unchanged signature; +1 route in the .cpp: the botanical PNG) ──
    std::optional<juce::WebBrowserComponent::Resource>
        getResource (const juce::String& url);

    // ── Native function registration (unchanged signature; −2 +3 functions in the .cpp) ──
    juce::WebBrowserComponent::Options addNativeFunctions (
        juce::WebBrowserComponent::Options options);

    // ── Timer: 30 Hz PUSH to the page through emitEventIfBrowserIsVisible ──
    //    (was: evaluateJavascript("window.updateHeldNotes(…)") — REMOVED, UI-04 /
    //    ARCHITECTURE Decision 7; completions are dropped while hidden, hence
    //    the *IfBrowserIsVisible* variant: memory critical_webview_completion_gated_on_isvisible)
    void timerCallback() override;

    // NEW — push helpers (bodies in the .cpp §5)
    void pushTerrainState (int osc, bool force);      // {osc, theta, x, y}, change-gated per oscillator
    void pushHeightmap    (int osc, bool force);      // {osc, n:64, data:<base64 Float32>} on generation change
    void pushStatus       (int osc, bool force);      // {osc, sourceMissing, fit, partials, approx}
    void pushHeldNotes    (bool force);               // {notes:[…], freqs:[…]}
    void repushAll();                                 // after preset apply / setStateInformation, and on request

    // NEW — change gates (one per oscillator where applicable)
    struct PlayheadSnapshot { float theta = 0.0f, x = 0.0f, y = 0.0f; bool operator== (const PlayheadSnapshot& o) const noexcept
                              { return theta == o.theta && x == o.x && y == o.y; } };
    PlayheadSnapshot lastPlayhead[2];
    uint32_t lastHeightmapGeneration[2] { 0, 0 };     // processorRef.getTerrainGeneration (osc): bumps on terrain-param change, PNG import, Chebyshev swap
    juce::String lastStatusJson[2];
    std::vector<std::pair<int, double>> lastSentNotes;   // unchanged
    bool repushPending = true;                        // set by requestTerrainRepush / preset apply; cleared in timerCallback

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (OStrataAudioProcessorEditor)
};
