#!/usr/bin/env python3
"""
Phase 2.4a R34c — emit SchellengCalibration.h from --matrix-stability JSON.

NO actual fitting. Trilinear over the 27-point grid is an exact interpolant;
this tool transcribes per-combo pass/fail into a constexpr array with
safeDepth = 1.0 for passing combos, 0.5 for failing combos (v1.0 fallback).

Usage:
    python3 tools/schelleng-fit/emit_table.py matrix.json --out path/SchellengCalibration.h
"""
import argparse
import hashlib
import json
import pathlib
import time


SPEED_AXIS = (0.05, 0.15, 0.5)
PRESS_AXIS = (1.0, 3.0, 7.0)
POS_AXIS   = (0.05, 0.10, 0.20)
STRING_NAMES = ("E1", "A1", "D2", "G2")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("matrix_json", type=pathlib.Path)
    p.add_argument("--out", type=pathlib.Path, required=True)
    args = p.parse_args()

    json_bytes = args.matrix_json.read_bytes()
    json_sha   = hashlib.sha256(json_bytes).hexdigest()
    data       = json.loads(json_bytes)

    assert data.get("mode") == "matrix-stability", "input is not matrix-stability JSON"
    assert data.get("totalCombos") == 108, "expected 108 combos"
    combos = data["combos"]
    assert len(combos) == 108

    # Build [4][3][3][3] table in canonical iteration order
    # (stringIdx -> speedIdx -> pressIdx -> posIdx).
    table = [[[[0.0] * 3 for _ in range(3)] for _ in range(3)] for _ in range(4)]
    for s in range(4):
        for i in range(3):
            for j in range(3):
                for k in range(3):
                    idx = s * 27 + i * 9 + j * 3 + k
                    e = combos[idx]
                    assert e["stringIdx"] == s, f"stringIdx mismatch at idx {idx}"
                    assert e["speedIdx"]  == i, f"speedIdx mismatch at idx {idx}"
                    assert e["pressIdx"]  == j, f"pressIdx mismatch at idx {idx}"
                    assert e["posIdx"]    == k, f"posIdx mismatch at idx {idx}"
                    table[s][i][j][k] = 1.0 if e["pass_combo"] else 0.5

    out = []
    out.append("// AUTO-GENERATED by tools/schelleng-fit/emit_table.py — DO NOT EDIT BY HAND.")
    out.append(f"// Generated: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}")
    out.append(f"// Source: matrix.json sha256: {json_sha}")
    out.append(f"// Status: {data.get('status', 'UNKNOWN')}  passCount: {data.get('passCount')}/{data.get('totalCombos')}")
    out.append(f"// Regenerate via: python3 tools/schelleng-fit/emit_table.py matrix.json --out <path>")
    out.append("")
    out.append("#pragma once")
    out.append("")
    out.append("#include <juce_core/juce_core.h>")
    out.append("")
    out.append("namespace ouaricon::contrabass::schelleng {")
    out.append("")
    out.append("inline constexpr int   kStrings   = 4;")
    out.append("inline constexpr int   kGridN     = 3;")
    out.append("inline constexpr float kSpeedAxis [3] = { 0.05f, 0.15f, 0.5f  };")
    out.append("inline constexpr float kPressAxis [3] = { 1.0f,  3.0f,  7.0f  };")
    out.append("inline constexpr float kPosAxis   [3] = { 0.05f, 0.10f, 0.20f };")
    out.append("")
    out.append("// safeDepth lookup table — indexed [stringIdx][speedIdx][pressIdx][posIdx].")
    out.append("// 1.0 = combo verified stable at SLOW_LFO_DEPTH=1.0; 0.5 = v1.0 fallback for failing combos.")
    out.append("inline constexpr float kSafeDepth[4][3][3][3] = {")
    for s in range(4):
        out.append(f"    /* {STRING_NAMES[s]} (stringIdx={s}) */ {{")
        for i in range(3):
            out.append(f"        /* speedIdx={i} (v_b={SPEED_AXIS[i]:g}) */ {{")
            for j in range(3):
                row = ", ".join(f"{table[s][i][j][k]:.1f}f" for k in range(3))
                trailing_comma = "," if j < 2 else ""
                out.append(f"            {{ {row} }}{trailing_comma}    // pressIdx={j} (F_bow={PRESS_AXIS[j]:g})")
            out.append("        }" + ("," if i < 2 else ""))
        out.append("    }" + ("," if s < 3 else ""))
    out.append("};")
    out.append("")
    out.append("// Trilinear interpolation lookup. Out-of-grid clamps to nearest edge (no extrapolation).")
    out.append("// Always returns float ∈ [0.0, 1.0]. Evaluation cost: 8 mul + 7 add + bounds.")
    out.append("//")
    out.append("// HR-8 — IEEE 754 identity arithmetic at grid sample points: when one weight is 1")
    out.append("// and the rest are 0, trilinear returns the corresponding c value exactly")
    out.append("// (x*1=x exact, x+0=x exact). emit_table.py's transcription assumption.")
    out.append("inline float safeDepthForString (int stringIdx, float v_b, float F_bow, float beta) noexcept")
    out.append("{")
    out.append("    auto interp_axis = [] (float x, const float (&axis)[3], int& lo, float& t) {")
    out.append("        if (x <= axis[0])      { lo = 0; t = 0.0f; }")
    out.append("        else if (x >= axis[2]) { lo = 1; t = 1.0f; }")
    out.append("        else if (x <= axis[1]) { lo = 0; t = (x - axis[0]) / (axis[1] - axis[0]); }")
    out.append("        else                   { lo = 1; t = (x - axis[1]) / (axis[2] - axis[1]); }")
    out.append("    };")
    out.append("    const int sIdx = juce::jlimit (0, 3, stringIdx);")
    out.append("    int iLo, jLo, kLo; float ti, tj, tk;")
    out.append("    interp_axis (v_b,   kSpeedAxis, iLo, ti);")
    out.append("    interp_axis (F_bow, kPressAxis, jLo, tj);")
    out.append("    interp_axis (beta,  kPosAxis,   kLo, tk);")
    out.append("    const float c000 = kSafeDepth[sIdx][iLo  ][jLo  ][kLo  ];")
    out.append("    const float c001 = kSafeDepth[sIdx][iLo  ][jLo  ][kLo+1];")
    out.append("    const float c010 = kSafeDepth[sIdx][iLo  ][jLo+1][kLo  ];")
    out.append("    const float c011 = kSafeDepth[sIdx][iLo  ][jLo+1][kLo+1];")
    out.append("    const float c100 = kSafeDepth[sIdx][iLo+1][jLo  ][kLo  ];")
    out.append("    const float c101 = kSafeDepth[sIdx][iLo+1][jLo  ][kLo+1];")
    out.append("    const float c110 = kSafeDepth[sIdx][iLo+1][jLo+1][kLo  ];")
    out.append("    const float c111 = kSafeDepth[sIdx][iLo+1][jLo+1][kLo+1];")
    out.append("    const float c00 = c000 * (1.0f - tk) + c001 * tk;")
    out.append("    const float c01 = c010 * (1.0f - tk) + c011 * tk;")
    out.append("    const float c10 = c100 * (1.0f - tk) + c101 * tk;")
    out.append("    const float c11 = c110 * (1.0f - tk) + c111 * tk;")
    out.append("    const float c0  = c00  * (1.0f - tj) + c01  * tj;")
    out.append("    const float c1  = c10  * (1.0f - tj) + c11  * tj;")
    out.append("    return juce::jlimit (0.0f, 1.0f, c0 * (1.0f - ti) + c1 * ti);")
    out.append("}")
    out.append("")
    out.append("} // namespace ouaricon::contrabass::schelleng")
    out.append("")

    args.out.write_text("\n".join(out))
    print(f"wrote {args.out} ({len(out)} lines)")


if __name__ == "__main__":
    main()
