; Inno Setup Script for {{PLUGIN_NAME}}
; Generated by Plugin Freedom System
;
; Template notes:
; - {{APP_GUID}} must be generated uniquely per plugin (use deterministic GUID from plugin name)
; - {{VST3_SOURCE_PATH}} points to the build artifact directory (the .vst3 folder)
; - {{OUTPUT_DIR}} is the dist/ output location (e.g., plugins/[PluginName]/dist)
; - {commonpf}\Common Files\VST3\ is the standard Windows VST3 location (C:\Program Files\Common Files\VST3\)
; - ArchitecturesInstallIn64BitMode=x64compatible ensures 64-bit installation
; - PrivilegesRequired=admin because writing to Program Files requires elevation
; - DisableDirPage=yes because VST3 install location is standardized

#define MyAppName "{{PRODUCT_NAME}}"
#define MyAppVersion "{{VERSION}}"
#define MyAppPublisher "Ouaricon Audio"
#define MyAppURL "https://ouaricon.audio"
#define MyPluginName "{{PLUGIN_NAME}}"

[Setup]
AppId={{{{APP_GUID}}}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
DefaultDirName={commonpf}\Common Files\VST3\{#MyAppName}.vst3
DisableDirPage=yes
DisableProgramGroupPage=yes
OutputDir={{OUTPUT_DIR}}
OutputBaseFilename={{PLUGIN_NAME}}-OuariconAudio-Setup
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible
UninstallDisplayName={#MyAppName} VST3 by Ouaricon Audio
LicenseFile=
SetupIconFile=
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
WelcomeLabel2=This will install {#MyAppName} v{#MyAppVersion} by Ouaricon Audio on your computer.%n%n{#MyAppName} is a VST3 audio plugin. After installation, open your DAW and scan for new plugins.

[Files]
; Install the VST3 bundle (entire directory tree)
Source: "{{VST3_SOURCE_PATH}}\*"; DestDir: "{commonpf}\Common Files\VST3\{#MyAppName}.vst3"; Flags: ignoreversion recursesubdirs createallsubdirs
; Microtonal Suite (Phase 25 v3 Path B) — bundled with every plugin install
; Lands at %APPDATA%\Ouaricon\Microtonal Suite\ for one-time Dorico Library Manager Import.
Source: "{{MICROTONAL_SUITE_DORICOLIB_PATH}}"; DestDir: "{userappdata}\Ouaricon\Microtonal Suite"; Flags: ignoreversion
Source: "{{MICROTONAL_SUITE_README_PATH}}"; DestDir: "{userappdata}\Ouaricon\Microtonal Suite"; Flags: ignoreversion

[Icons]
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"

[Run]
; No post-install actions needed for VST3

[UninstallDelete]
Type: filesandordirs; Name: "{commonpf}\Common Files\VST3\{#MyAppName}.vst3"

[Code]
// Optional: Clear DAW plugin caches after install
procedure CurStepChanged(CurStep: TSetupStep);
var
  AbletonDir: String;
begin
  if CurStep = ssPostInstall then
  begin
    // Clear Ableton plugin cache (optional, non-fatal)
    AbletonDir := ExpandConstant('{userappdata}\Ableton');
    if DirExists(AbletonDir) then
    begin
      // Ableton will rescan on next launch
      Log('Ableton preferences directory found - plugin rescan will occur on next launch');
    end;
    // Microtonal Suite (Phase 25 v3 Path B) installed via [Files]; user activates via:
    //   Dorico -> Library -> Library Manager -> Import... -> select Ouaricon-VST3-NoteExpression.doricolib
    Log('[Ouaricon] Microtonal Suite installed at: ' + ExpandConstant('{userappdata}\Ouaricon\Microtonal Suite'));
    Log('[Ouaricon] Activate in Dorico via Library -> Library Manager -> Import...');
  end;
end;
