/*
   This file is part of O-Contrabass, an Ouaricon Audio plugin.
   Copyright (C) 2026  Ouaricon Audio

   SPDX-License-Identifier: AGPL-3.0-or-later

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU Affero General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU Affero General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// AUTO-GENERATED by tools/schelleng-fit/emit_table.py — DO NOT EDIT BY HAND.
// Generated: 2026-04-28 17:57:59 UTC
// Source: matrix.json sha256: 625505cf14fc3e0563c12fced47d958407afe8af91722c28a3ca41eb899236fa
// Status: FAIL  passCount: 105/108
// Regenerate via: python3 tools/schelleng-fit/emit_table.py matrix.json --out <path>

#pragma once

#include <juce_core/juce_core.h>

namespace ouaricon::contrabass::schelleng {

inline constexpr int   kStrings   = 4;
inline constexpr int   kGridN     = 3;
inline constexpr float kSpeedAxis [3] = { 0.05f, 0.15f, 0.5f  };
inline constexpr float kPressAxis [3] = { 1.0f,  3.0f,  7.0f  };
inline constexpr float kPosAxis   [3] = { 0.05f, 0.10f, 0.20f };

// safeDepth lookup table — indexed [stringIdx][speedIdx][pressIdx][posIdx].
// 1.0 = combo verified stable at SLOW_LFO_DEPTH=1.0; 0.5 = v1.0 fallback for failing combos.
inline constexpr float kSafeDepth[4][3][3][3] = {
    /* E1 (stringIdx=0) */ {
        /* speedIdx=0 (v_b=0.05) */ {
            { 1.0f, 1.0f, 1.0f },    // pressIdx=0 (F_bow=1)
            { 1.0f, 1.0f, 1.0f },    // pressIdx=1 (F_bow=3)
            { 1.0f, 1.0f, 1.0f }    // pressIdx=2 (F_bow=7)
        },
        /* speedIdx=1 (v_b=0.15) */ {
            { 1.0f, 1.0f, 1.0f },    // pressIdx=0 (F_bow=1)
            { 1.0f, 1.0f, 1.0f },    // pressIdx=1 (F_bow=3)
            { 1.0f, 1.0f, 1.0f }    // pressIdx=2 (F_bow=7)
        },
        /* speedIdx=2 (v_b=0.5) */ {
            { 0.5f, 1.0f, 1.0f },    // pressIdx=0 (F_bow=1)
            { 1.0f, 1.0f, 1.0f },    // pressIdx=1 (F_bow=3)
            { 1.0f, 1.0f, 1.0f }    // pressIdx=2 (F_bow=7)
        }
    },
    /* A1 (stringIdx=1) */ {
        /* speedIdx=0 (v_b=0.05) */ {
            { 1.0f, 1.0f, 1.0f },    // pressIdx=0 (F_bow=1)
            { 1.0f, 1.0f, 1.0f },    // pressIdx=1 (F_bow=3)
            { 1.0f, 1.0f, 1.0f }    // pressIdx=2 (F_bow=7)
        },
        /* speedIdx=1 (v_b=0.15) */ {
            { 1.0f, 1.0f, 1.0f },    // pressIdx=0 (F_bow=1)
            { 1.0f, 1.0f, 1.0f },    // pressIdx=1 (F_bow=3)
            { 1.0f, 1.0f, 1.0f }    // pressIdx=2 (F_bow=7)
        },
        /* speedIdx=2 (v_b=0.5) */ {
            { 0.5f, 1.0f, 1.0f },    // pressIdx=0 (F_bow=1)
            { 1.0f, 1.0f, 1.0f },    // pressIdx=1 (F_bow=3)
            { 1.0f, 1.0f, 1.0f }    // pressIdx=2 (F_bow=7)
        }
    },
    /* D2 (stringIdx=2) */ {
        /* speedIdx=0 (v_b=0.05) */ {
            { 1.0f, 1.0f, 1.0f },    // pressIdx=0 (F_bow=1)
            { 1.0f, 1.0f, 1.0f },    // pressIdx=1 (F_bow=3)
            { 1.0f, 1.0f, 1.0f }    // pressIdx=2 (F_bow=7)
        },
        /* speedIdx=1 (v_b=0.15) */ {
            { 1.0f, 1.0f, 1.0f },    // pressIdx=0 (F_bow=1)
            { 1.0f, 1.0f, 1.0f },    // pressIdx=1 (F_bow=3)
            { 1.0f, 1.0f, 1.0f }    // pressIdx=2 (F_bow=7)
        },
        /* speedIdx=2 (v_b=0.5) */ {
            { 0.5f, 1.0f, 1.0f },    // pressIdx=0 (F_bow=1)
            { 1.0f, 1.0f, 1.0f },    // pressIdx=1 (F_bow=3)
            { 1.0f, 1.0f, 1.0f }    // pressIdx=2 (F_bow=7)
        }
    },
    /* G2 (stringIdx=3) */ {
        /* speedIdx=0 (v_b=0.05) */ {
            { 1.0f, 1.0f, 1.0f },    // pressIdx=0 (F_bow=1)
            { 1.0f, 1.0f, 1.0f },    // pressIdx=1 (F_bow=3)
            { 1.0f, 1.0f, 1.0f }    // pressIdx=2 (F_bow=7)
        },
        /* speedIdx=1 (v_b=0.15) */ {
            { 1.0f, 1.0f, 1.0f },    // pressIdx=0 (F_bow=1)
            { 1.0f, 1.0f, 1.0f },    // pressIdx=1 (F_bow=3)
            { 1.0f, 1.0f, 1.0f }    // pressIdx=2 (F_bow=7)
        },
        /* speedIdx=2 (v_b=0.5) */ {
            { 1.0f, 1.0f, 1.0f },    // pressIdx=0 (F_bow=1)
            { 1.0f, 1.0f, 1.0f },    // pressIdx=1 (F_bow=3)
            { 1.0f, 1.0f, 1.0f }    // pressIdx=2 (F_bow=7)
        }
    }
};

// Trilinear interpolation lookup. Out-of-grid clamps to nearest edge (no extrapolation).
// Always returns float ∈ [0.0, 1.0]. Evaluation cost: 8 mul + 7 add + bounds.
//
// HR-8 — IEEE 754 identity arithmetic at grid sample points: when one weight is 1
// and the rest are 0, trilinear returns the corresponding c value exactly
// (x*1=x exact, x+0=x exact). emit_table.py's transcription assumption.
inline float safeDepthForString (int stringIdx, float v_b, float F_bow, float beta) noexcept
{
    auto interp_axis = [] (float x, const float (&axis)[3], int& lo, float& t) {
        if (x <= axis[0])      { lo = 0; t = 0.0f; }
        else if (x >= axis[2]) { lo = 1; t = 1.0f; }
        else if (x <= axis[1]) { lo = 0; t = (x - axis[0]) / (axis[1] - axis[0]); }
        else                   { lo = 1; t = (x - axis[1]) / (axis[2] - axis[1]); }
    };
    const int sIdx = juce::jlimit (0, 3, stringIdx);
    int iLo, jLo, kLo; float ti, tj, tk;
    interp_axis (v_b,   kSpeedAxis, iLo, ti);
    interp_axis (F_bow, kPressAxis, jLo, tj);
    interp_axis (beta,  kPosAxis,   kLo, tk);
    const float c000 = kSafeDepth[sIdx][iLo  ][jLo  ][kLo  ];
    const float c001 = kSafeDepth[sIdx][iLo  ][jLo  ][kLo+1];
    const float c010 = kSafeDepth[sIdx][iLo  ][jLo+1][kLo  ];
    const float c011 = kSafeDepth[sIdx][iLo  ][jLo+1][kLo+1];
    const float c100 = kSafeDepth[sIdx][iLo+1][jLo  ][kLo  ];
    const float c101 = kSafeDepth[sIdx][iLo+1][jLo  ][kLo+1];
    const float c110 = kSafeDepth[sIdx][iLo+1][jLo+1][kLo  ];
    const float c111 = kSafeDepth[sIdx][iLo+1][jLo+1][kLo+1];
    const float c00 = c000 * (1.0f - tk) + c001 * tk;
    const float c01 = c010 * (1.0f - tk) + c011 * tk;
    const float c10 = c100 * (1.0f - tk) + c101 * tk;
    const float c11 = c110 * (1.0f - tk) + c111 * tk;
    const float c0  = c00  * (1.0f - tj) + c01  * tj;
    const float c1  = c10  * (1.0f - tj) + c11  * tj;
    return juce::jlimit (0.0f, 1.0f, c0 * (1.0f - ti) + c1 * ti);
}

} // namespace ouaricon::contrabass::schelleng
