/*
   This file is part of O-Strata, an Ouaricon Audio plugin.
   Copyright (C) 2026  Ouaricon Audio

   SPDX-License-Identifier: AGPL-3.0-or-later
   (full AGPL header block verbatim from plugins/O-Prism/Source/PluginEditor.cpp)
*/
/*
  ==============================================================================

    PluginEditor.cpp — TEMPLATE v1 (generated by ui-finalization-agent, 2026-09-07)
    O-Strata — DELTA against plugins/O-Prism/Source/PluginEditor.cpp (v1.24.0)

    Stage 3 gui-agent: start from O-Prism's file, rename the class, then apply
    the sections below in order. "unchanged from O-Prism" = keep verbatim.
    Window: setSize (1200, 800) — from v1-ui.yaml `window:` (unchanged).

  ==============================================================================
*/

#include "PluginEditor.h"
#include "EmbeddedTunings.h"
#include "TuningExporter.h"
#include "dsp/ModulationMatrix.h"

// ═══════════════════════════════════════════════════════════════════
// §0  PrismParamIds.h DELTA (Stage 1 — shown here because the editor's
//     relay loop is driven by it; parameter-spec.md "all 48 IDs in APVTS order")
// ═══════════════════════════════════════════════════════════════════
/*
    inline juce::StringArray oscIds (const juce::String& prefix)
    {
        juce::StringArray ids;
        for (const auto* s : { //  "Table",   ← REMOVED (oscATable / oscBTable)
                                "Pos", "Level", "Pan", "Coarse", "Fine", "Phase",
                                "Unison", "Detune", "Width", "WarpType", "WarpAmt",   // 11 carried over
                                // ── NEW: Geometry block, 24 per oscillator, all bake params ──
                                "GeoSource", "GeoFrames", "GeoDrive",                                          // common 3
                                "Mesh", "MeshTiltX", "MeshTiltY", "MeshPhi", "MeshUnwrap", "MeshLoop",         // mesh 6
                                "VolField", "VolOrbit", "VolSweepAxis", "VolSweepRange", "VolDetail",          // volume 5
                                "Terrain", "TerOrbit", "TerCX", "TerCY", "TerAspect", "TerRot",
                                "TerSweepAxis", "TerSweepRange", "TerBlur", "TerEdge" })                       // terrain 10
            ids.add (prefix + s);
        return ids;                                                                   // 35 per oscillator
    }

    // allSliderIds(): oscIds("oscA") + oscIds("oscB") now contribute 70 (was 24);
    // everything after is unchanged → 187 total (O-Prism's `// 126` comment was
    // already stale; the array held 141). Fix the comment.
    // Optional one-line Stage 1 fix flagged in parameter-spec.md: add "delayDivision"
    // to the delay group so its dropdown gets a relay (unbound in O-Prism).

    // NEW helper for the bake scheduler + mod-matrix destination exclusion:
    inline bool isGeometryParam (const juce::String& id)
    {
        return id.startsWith ("oscA") || id.startsWith ("oscB")
             ? (id.contains ("Geo") || id.contains ("Mesh") || id.contains ("Vol") || id.contains ("Ter"))
             : false;
    }
*/

// ═══════════════════════════════════════════════════════════════════
// §1  Toggle relay helpers — unchanged from O-Prism (createToggleRelays,
//     addRelayOptions, attachToggleRelays)
// ═══════════════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════════════
// §2  Resource provider — DELTA
//     makeBinaryResource() unchanged. URLs are bare PATHS (memory
//     critical_webview_resource_provider_and_schemes). Every embedded file must
//     ALSO be served here (check-i18n assertion 8 asserts both halves).
// ═══════════════════════════════════════════════════════════════════
std::optional<juce::WebBrowserComponent::Resource>
OStrataAudioProcessorEditor::getResource (const juce::String& url)
{
    if (url == "/" || url == "/index.html")
        return makeBinaryResource (BinaryData::index_html, BinaryData::index_htmlSize, "text/html");

    if (url == "/js/i18n.js")
        return makeBinaryResource (BinaryData::i18n_js, BinaryData::i18n_jsSize, "application/javascript");

    if (url == "/js/juce/index.js")
        return makeBinaryResource (BinaryData::index_js, BinaryData::index_jsSize, "application/javascript");

    if (url == "/js/juce/check_native_interop.js")
        return makeBinaryResource (BinaryData::check_native_interop_js, BinaryData::check_native_interop_jsSize, "application/javascript");

    // REMOVED: "/js/wavetable-editor.js", "/css/wavetable-editor.css"

    // NEW (Stage 3.2): WebGL2 + Canvas 2D renderer module. Symbol has the hyphen STRIPPED.
    if (url == "/js/geometry-view.js")
        return makeBinaryResource (BinaryData::geometryview_js, BinaryData::geometryview_jsSize, "application/javascript");

    // NEW: Geometry-tab botanical overlay (v1-ui.yaml layout.geometry_tab.botanical_overlay)
    if (url == "/img/shell_conchologiaiconi12reev_0090.png")
        return makeBinaryResource (BinaryData::shell_conchologiaiconi12reev_0090_png,
                                   BinaryData::shell_conchologiaiconi12reev_0090_pngSize, "image/png");

    // NEW (Stage 3.2): decimated view mesh, ≤ 8 k triangles, built in the bake job.
    // The generation number in the path defeats WKWebView caching. Layout:
    //   uint32 nu, uint32 nv, then (nu+1)*(nv+1) xyz float32 (grid form).
    if (url.startsWith ("/geo/mesh-"))
    {
        const int osc = url.contains ("mesh-A-") ? 0 : 1;
        if (auto blob = processorRef.getViewMeshBlob (osc))     // shared_ptr<const MemoryBlock>, message thread only
        {
            auto* p = static_cast<const std::byte*> (blob->getData());
            return juce::WebBrowserComponent::Resource { std::vector<std::byte> (p, p + blob->getSize()),
                                                         juce::String ("application/octet-stream") };
        }
        return std::nullopt;
    }

    return std::nullopt;
}

// §3  JSON helpers (toJsonArray, toJsonFloatArray) and syncTuningPresetToCustom — unchanged.

// NEW: base64 Float32 encoder for the view table / polylines (never JSON floats —
// a 64×64 table as JSON text is ~40 KB, as base64 Float32 it is ~21 KB and one memcpy)
static juce::String toBase64Float32 (const float* data, int count)
{
    return juce::Base64::toBase64 (data, static_cast<size_t> (count) * sizeof (float));
}

// ═══════════════════════════════════════════════════════════════════
// §4  Native functions — DELTA
// ═══════════════════════════════════════════════════════════════════
juce::WebBrowserComponent::Options
OStrataAudioProcessorEditor::addNativeFunctions (juce::WebBrowserComponent::Options options)
{
    // ── unchanged from O-Prism ──
    //   getUiLanguage, setUiLanguage,
    //   getTuningIntervals, getTuningName, setSingleInterval, setTonicNote, getTonicNote,
    //   getOctaveStretch, loadScalaFile, loadKBMFile, saveScalaFile, saveKBMFile,
    //   generateEDO, generateHarmonicSeries, generateRank2, getEmbeddedTuningList,
    //   loadEmbeddedTuning, applyGeneratedScale, exportTuningHTML,
    //   getModSourceNames, getModDestNames   (dest list = O-Prism's 26 entries — no Geometry ids),
    //   getPresetListWithCategories, getCurrentPreset, loadPresetFromCategory, loadPresetByName,
    //   selectNextPreset, selectPreviousPreset, savePreset, isFactoryPreset,
    //   getActiveOscInfo, getActiveOscFrame   (rewired in the processor to the PUBLISHED table — UI-04)

    // ── REMOVED (ARCHITECTURE Decision 5) — 14 wavetable-library fns ──
    //   getUserWavetableList, importUserWavetable, importUserWavetableData, selectUserWavetable,
    //   clearUserWavetableOverride, deleteUserWavetable, startWavetableEditor, stopWavetableEditor,
    //   getEditorFrameWaveform, getFrameHarmonics, setFrameHarmonics, applyFrameOperation,
    //   saveEditedWavetable, getAllEditorFrameWaveforms

    // ── NEW: importGeometry(osc) — file chooser (FUNC-06/07, ROADMAP 3.3) ──
    // Pattern: memory pattern_webview_launchasync_safepointer_no_complete —
    // capture a SafePointer, bail WITHOUT calling complete() if the editor is
    // gone (complete holds a raw pointer into the dead WebView pimpl).
    options = options.withNativeFunction ("importGeometry",
        [this] (const juce::Array<juce::var>& args, auto complete)
        {
            const int osc = (args.size() > 0 && args[0].toString() == "B") ? 1 : 0;
            auto chooser = std::make_shared<juce::FileChooser> (
                "Import geometry (OBJ, STL) or heightmap (PNG)",
                juce::File::getSpecialLocation (juce::File::userDocumentsDirectory),
                "*.obj;*.stl;*.png");

            juce::Component::SafePointer<OStrataAudioProcessorEditor> safeThis (this);
            chooser->launchAsync (juce::FileBrowserComponent::openMode | juce::FileBrowserComponent::canSelectFiles,
                [safeThis, chooser, complete, osc] (const juce::FileChooser& fc)
                {
                    if (safeThis == nullptr)
                        return;                                  // editor destroyed while the dialog was open — do NOT call complete()

                    auto file = fc.getResult();
                    if (! file.existsAsFile())
                    {
                        complete (juce::var (false));
                        return;
                    }

                    juce::MemoryBlock bytes;
                    file.loadFileAsData (bytes);                 // message thread: read only. Parse happens in the bake job (Decision 6).
                    safeThis->processorRef.submitGeometryImport (osc, file.getFileName(), std::move (bytes), file.getFullPathName());
                    complete (juce::var (true));                 // success = bytes handed to the scheduler; the bake result arrives as a geometryState event
                });
        });

    // ── NEW: importGeometryChunk(osc, name, base64) — drag-and-drop streaming ──
    // WKWebView strips file paths; the page reads the file via webkitGetAsEntry
    // and streams ≤ 4 MB base64 chunks (memory critical_webview_drag_drop_macos).
    // Standard base64 → juce::Base64::convertFromBase64, NEVER MemoryBlock::fromBase64Encoding.
    options = options.withNativeFunction ("importGeometryChunk",
        [this] (const juce::Array<juce::var>& args, auto complete)
        {
            if (args.size() < 3) { complete (juce::var (false)); return; }
            const int osc = args[0].toString() == "B" ? 1 : 0;
            if (pendingImportName[osc] != args[1].toString())
            {
                pendingImport[osc].reset();
                pendingImportName[osc] = args[1].toString();
            }
            const bool ok = juce::Base64::convertFromBase64 (pendingImport[osc], args[2].toString());
            complete (juce::var (ok));
        });

    // ── NEW: importGeometryCommit(osc, name, totalBytes) ──
    options = options.withNativeFunction ("importGeometryCommit",
        [this] (const juce::Array<juce::var>& args, auto complete)
        {
            if (args.size() < 2) { complete (juce::var (false)); return; }
            const int osc = args[0].toString() == "B" ? 1 : 0;
            pendingImport[osc].flush();
            juce::MemoryBlock bytes (pendingImport[osc].getData(), pendingImport[osc].getDataSize());
            pendingImport[osc].reset();
            processorRef.submitGeometryImport (osc, args[1].toString(), std::move (bytes), {});   // no path: drag-drop is always embedded (or rejected above the 2 MB cap with a notice)
            pendingImportName[osc].clear();
            complete (juce::var (true));
        });

    // ── NEW: setViewMode(osc, "3d"|"wt") — UI state mirror, not a parameter ──
    options = options.withNativeFunction ("setViewMode",
        [this] (const juce::Array<juce::var>& args, auto complete)
        {
            if (args.size() >= 2)
            {
                const int osc = args[0].toString() == "B" ? 1 : 0;
                viewMode[osc] = args[1].toString() == "wt" ? 1 : 0;
                lastBakeGeneration[osc] = -1;                    // force a geometryState re-push with the right payload
            }
            complete (juce::var());
        });

    // ── NEW (debug, PERF-03 gate): reportDrawStats(mean, max) — logged, not persisted ──
    options = options.withNativeFunction ("reportDrawStats",
        [] (const juce::Array<juce::var>& args, auto complete)
        {
            if (args.size() >= 2)
                DBG ("geo-view draw ms: mean " << (double) args[0] << " max " << (double) args[1]);
            complete (juce::var());
        });

    return options;
}

// ═══════════════════════════════════════════════════════════════════
// §5  Constructor — unchanged from O-Prism apart from the class name and the
//     WebView2 user-data folder. Order: relays → options (.withOptionsFrom for
//     EVERY relay) → native fns → WebView → attachments → show → setSize → timer.
//     The 48 geometry relays fall out of the `for (id : sliderIds)` loops.
// ═══════════════════════════════════════════════════════════════════
OStrataAudioProcessorEditor::OStrataAudioProcessorEditor (OStrataAudioProcessor& p)
    : AudioProcessorEditor (p),
      processorRef (p)
{
    // Step 1: relays (before WebView) — unchanged
    auto sliderIds    = PrismParamIds::allSliderIds();          // 187
    auto bypassIds    = PrismParamIds::bypassToggleIds();
    auto modToggleIds = PrismParamIds::modSlotToggleIds();
    juce::StringArray lfoSyncIds, lfoFreeRunIds;
    for (int i = 1; i <= 4; ++i) { lfoSyncIds.add ("lfo" + juce::String (i) + "Sync"); lfoFreeRunIds.add ("lfo" + juce::String (i) + "FreeRun"); }

    for (const auto& id : sliderIds)
        sliderRelays.push_back (std::make_unique<juce::WebSliderRelay> (id));
    delaySyncRelay = std::make_unique<juce::WebToggleButtonRelay> ("delaySync");
    createToggleRelays (lfoSyncIds, lfoSyncRelays);
    createToggleRelays (lfoFreeRunIds, lfoFreeRunRelays);
    for (const auto& id : bypassIds)    bypassRelays.push_back (std::make_unique<juce::WebToggleButtonRelay> (id));
    for (const auto& id : modToggleIds) modSlotToggleRelays.push_back (std::make_unique<juce::WebToggleButtonRelay> (id));

    // Step 2: options — unchanged
    auto options = juce::WebBrowserComponent::Options{}
        .withBackend (juce::WebBrowserComponent::Options::Backend::webview2)
        .withNativeIntegrationEnabled()
        .withResourceProvider ([this] (const auto& url) { return getResource (url); });

    for (const auto& relay : sliderRelays)        options = options.withOptionsFrom (*relay);
    options = options.withOptionsFrom (*delaySyncRelay);
    addRelayOptions (lfoSyncRelays, options);
    addRelayOptions (lfoFreeRunRelays, options);
    for (const auto& relay : bypassRelays)        options = options.withOptionsFrom (*relay);
    for (const auto& relay : modSlotToggleRelays) options = options.withOptionsFrom (*relay);
    options = addNativeFunctions (options);

   #if JUCE_WINDOWS
    options = options.withWinWebView2Options (
        juce::WebBrowserComponent::Options::WinWebView2{}
            .withUserDataFolder (juce::File::getSpecialLocation (juce::File::tempDirectory)
                                     .getChildFile ("OStrata_WebView")));          // renamed from OPrism_WebView
   #endif

    webView = std::make_unique<juce::WebBrowserComponent> (options);

    // Step 3: attachments (after WebView) — unchanged; the geometry attachments are
    // created by the same loop (three-argument ctor: param, relay, nullptr undo manager)
    for (int i = 0; i < sliderIds.size(); ++i)
        if (auto* param = processorRef.getAPVTS().getParameter (sliderIds[i]))
            sliderAttachments.push_back (std::make_unique<juce::WebSliderParameterAttachment> (*param, *sliderRelays[static_cast<size_t> (i)], nullptr));
    // delaySync / lfo / bypass / modSlot attachments — unchanged from O-Prism
    jassert (sliderAttachments.size() == sliderRelays.size());                     // 187 == 187: every ID in allSliderIds() exists in the APVTS

    // Step 4: show + navigate — unchanged
    addAndMakeVisible (*webView);
    webView->goToURL (juce::WebBrowserComponent::getResourceProviderRoot());
    setSize (1200, 800);                                                           // v1-ui.yaml window: 1200 × 800, not resizable
    startTimerHz (30);                                                             // playhead + held notes at 30 Hz; bake progress every 3rd tick
}

OStrataAudioProcessorEditor::~OStrataAudioProcessorEditor() { stopTimer(); }      // unchanged
// paint() / resized() — unchanged from O-Prism

// ═══════════════════════════════════════════════════════════════════
// §6  Timer — REPLACED (ARCHITECTURE Decision 7). No evaluateJavascript.
//     emitEventIfBrowserIsVisible drops events while the view is hidden (no
//     queue growth) and returns false — the "last sent" caches are only
//     updated on a successful emit so the next visible tick re-sends.
// ═══════════════════════════════════════════════════════════════════
void OStrataAudioProcessorEditor::timerCallback()
{
    if (webView == nullptr)
        return;

    ++tickCounter;

    pushHeldNotesIfChanged();                                  // TrueKeys (was evaluateJavascript)

    // Re-push gate: preset apply / setStateInformation / bake completion bump these
    const int importRev = processorRef.getImportRevision();
    for (int osc = 0; osc < 2; ++osc)
    {
        const int gen = processorRef.getBakeGeneration (osc);
        if (gen != lastBakeGeneration[osc] || importRev != lastImportRevision)
            pushGeometryState (osc);                           // sets lastBakeGeneration[osc] on success

        pushPlayheadIfChanged (osc);                           // 30 Hz, change-gated, < 100 bytes
        if ((tickCounter % 3) == 0)
            pushBakeProgressIfChanged (osc);                   // 10 Hz while baking (UI-04)
    }
    lastImportRevision = importRev;
}

void OStrataAudioProcessorEditor::pushHeldNotesIfChanged()
{
    auto currentNotes = processorRef.getActiveNotes();
    if (currentNotes == lastSentNotes)
        return;

    juce::DynamicObject::Ptr obj = new juce::DynamicObject();
    juce::Array<juce::var> notes, freqs;
    for (const auto& n : currentNotes) { notes.add (n.first); freqs.add (n.second); }
    obj->setProperty ("notes", notes);
    obj->setProperty ("freqs", freqs);

    if (webView->emitEventIfBrowserIsVisible ("heldNotes", juce::var (obj.get())))
        lastSentNotes = std::move (currentNotes);
}

void OStrataAudioProcessorEditor::pushPlayheadIfChanged (int osc)
{
    // Frame from the Position parameter + GeoFrames; phase from the most recently
    // triggered voice's oscillator (atomic snapshot the voice already keeps for
    // O-Prism's display). Quantised so unchanged state sends nothing.
    const auto snap  = processorRef.getPlayheadSnapshot (osc);           // { int frame; float phase; }
    const float ph   = std::round (snap.phase * 100.0f) / 100.0f;
    if (snap.frame == lastPlayhead[osc].frame && ph == lastPlayhead[osc].phase)
        return;

    juce::DynamicObject::Ptr obj = new juce::DynamicObject();
    obj->setProperty ("osc",   osc == 0 ? "A" : "B");
    obj->setProperty ("frame", snap.frame);
    obj->setProperty ("phase", ph);
    if (webView->emitEventIfBrowserIsVisible ("geoPlayhead", juce::var (obj.get())))
        lastPlayhead[osc] = { snap.frame, ph };
}

void OStrataAudioProcessorEditor::pushBakeProgressIfChanged (int osc)
{
    const bool  baking   = processorRef.isBakeInFlight (osc);
    const float progress = processorRef.getBakeProgress (osc);           // 0..1, atomic
    if (baking == lastBaking[osc] && std::abs (progress - lastBakeProgress[osc]) < 0.02f)
        return;

    juce::DynamicObject::Ptr obj = new juce::DynamicObject();
    obj->setProperty ("osc",      osc == 0 ? "A" : "B");
    obj->setProperty ("baking",   baking);
    obj->setProperty ("progress", progress);
    if (webView->emitEventIfBrowserIsVisible ("bakeProgress", juce::var (obj.get())))
    {
        lastBaking[osc] = baking;
        lastBakeProgress[osc] = progress;
    }
}

void OStrataAudioProcessorEditor::pushGeometryState (int osc)
{
    // Everything here was built in the bake job and published to the message
    // thread with callAsync; this function only serialises. The full 256×2048
    // table NEVER crosses as text (largest event ≤ 32 KB; mesh goes via .bin).
    const auto view = processorRef.getViewCache (osc);                   // shared_ptr<const GeometryViewCache> — may be null before the first bake
    if (view == nullptr)
        return;

    juce::DynamicObject::Ptr obj = new juce::DynamicObject();
    obj->setProperty ("osc",           osc == 0 ? "A" : "B");
    obj->setProperty ("generation",    view->generation);
    obj->setProperty ("family",        view->familyName);                // "mesh" | "volume" | "terrain"
    obj->setProperty ("frames",        view->frameCount);
    obj->setProperty ("bakeMs",        view->bakeMilliseconds);
    obj->setProperty ("sourceMissing", view->sourceMissing);             // QUAL-03 notice
    obj->setProperty ("warnings",      view->warningBits);               // open-mesh / degenerate flags
    obj->setProperty ("viewW",         64);
    obj->setProperty ("view",          toBase64Float32 (view->table64x64.data(), 64 * 64));               // heightmap (terrain) or stacked-frame decimation (≋ mode) — ~21 KB
    if (! view->contour.empty()) obj->setProperty ("contour", toBase64Float32 (view->contour.data(), (int) view->contour.size()));   // xyz triples, ≤ 512 pts
    if (! view->orbit.empty())   obj->setProperty ("orbit",   toBase64Float32 (view->orbit.data(),   (int) view->orbit.size()));     // 512 pts
    obj->setProperty ("meshUrl", view->hasViewMesh ? juce::var ("geo/mesh-" + juce::String (osc == 0 ? "A" : "B") + "-" + juce::String (view->generation) + ".bin")
                                                   : juce::var());

    if (webView->emitEventIfBrowserIsVisible ("geometryState", juce::var (obj.get())))
        lastBakeGeneration[osc] = view->generation;                      // not updated when hidden → re-sent on the next visible tick
}

/*  ── Processor-side API this template assumes (Stage 1/2 add these to OStrataAudioProcessor) ──
    int   getImportRevision() const;                         // atomic; ++ on import / setStateInformation / preset apply
    int   getBakeGeneration (int osc) const;                 // atomic; ++ on every publish
    bool  isBakeInFlight (int osc) const;  float getBakeProgress (int osc) const;
    struct PlayheadSnapshot { int frame; float phase; };  PlayheadSnapshot getPlayheadSnapshot (int osc) const;
    std::shared_ptr<const GeometryViewCache> getViewCache (int osc) const;     // message thread
    std::shared_ptr<const juce::MemoryBlock>  getViewMeshBlob (int osc) const; // message thread
    void  submitGeometryImport (int osc, const juce::String& name, juce::MemoryBlock&& bytes, const juce::String& pathOrEmpty);
    std::vector<std::pair<int, double>> getActiveNotes() const;               // inherited
*/
